version: '3.8'
services:
  steamate:
    container_name: steamate
    build:
      context: ./steamate
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: 3.12.9
      cache_from:
        - steamate:latest
    volumes:
      - ./steamate:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: sh -c "python manage.py migrate && python manage.py load_data && gunicorn config.wsgi:application --bind 0.0.0.0:8000 --forwarded-allow-ips '*'"
    networks:
      - steamate-network

  nginx:
    build:
      context: ./nginx
      args:
        NGINX_VERSION: 1.24.0
    container_name: nginx
    restart: "on-failure"
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - steamate
    networks:
      - steamate-network
    

networks:
  steamate-network:
    driver: bridge


